"use strict";
import { version, name, author, mail, homepage } from "../../package.json";
import fs from "fs";
import utils from "./utils.js";

class Iso {
  constructor(
    homeDir = "/srv/incubator",
    distroName,
    clientUserFullName,
    clientUserName,
    clientPassword
  ) {
    this.distroRoot = homeDir + `${distroName}`;
    this.fsDir = homeDir + `${distroName}/fs`;
    this.isoDir = homeDir + `${distroName}/iso`;
    this.distroName = distroName;

    this.clientUserFullName = clientUserFullName;
    this.clientUserName = clientUserName;
    this.clientPassword = clientPassword;
    this.clientIpAddress = "127.0.1.1";

    this.kernelVer = utils.kernerlVersion();
    this.netDomainName = utils.netDomainName();
  }

  show() {
    console.log("eggs: incubator iso parameters ");
    console.log(">>> kernelVer: " + this.kernelVer);
    console.log(">>> netDomainName: " + this.netDomainName);
  }

  create() {
    console.log("==========================================");
    console.log("Incubator iso: create");
    console.log("==========================================");
    if (!fs.existsSync(this.isoDir)) {
      utils.exec(`mkdir -p ${this.isoDir}/live`);
      utils.exec(`mkdir -p ${this.isoDir}/isolinux`);
      utils.exec(`mkdir -p ${this.isoDir}/EFI`);
      utils.exec(`mkdir -p ${this.isoDir}/boot`);
    }
  }

  erase() {
    console.log("==========================================");
    console.log("Incubator iso: erase");
    console.log("==========================================");
    utils.exec(`rm -rf ${this.isoDir}`);
  }

  install() {
    utils.exec(`apt-get update`);
    utils.exec(
      `apt-get install squashfs-tools xorriso live-boot syslinux syslinux-common isolinux -y`
    );
  }

  purge() {
    utils.exec(
      //live-boot-initramfs-tools live-config live-config-systemd`
      `apt-get remove --purge squashfs-tools xorriso live-boot syslinux syslinux-common isolinux -y`
    );
  }
  fstab() {
    let file = `${this.fsDir}/etc/fstab`;
    let text = `
#proc /proc proc defaults 0 0
`;
    utils.bashwrite(file, text);
  }

  isolinux() {
    let isolinuxbin = "/usr/lib/ISOLINUX/isolinux.bin";
    let vesamenu = "/usr/lib/syslinux/modules/bios/vesamenu.c32";

    utils.exec(
      `rsync -a /usr/lib/syslinux/modules/bios/chain.c32 ${this
        .isoDir}/isolinux/`
    );
    utils.exec(
      `rsync -a /usr/lib/syslinux/modules/bios/ldlinux.c32 ${this
        .isoDir}/isolinux/`
    );
    utils.exec(
      `rsync -a /usr/lib/syslinux/modules/bios/libcom32.c32 ${this
        .isoDir}/isolinux/`
    );
    utils.exec(
      `rsync -a /usr/lib/syslinux/modules/bios/libutil.c32 ${this
        .isoDir}/isolinux/`
    );
    utils.exec(`rsync -a ${isolinuxbin} ${this.isoDir}/isolinux/`);
    utils.exec(`rsync -a ${vesamenu} ${this.isoDir}/isolinux/`);
  }

  isolinuxCfg() {
    let file = `${this.isoDir}/isolinux/isolinux.cfg`;
    let d= new Date();
    let at = pad(d.getUTCFullYear()) + "/" +
              pad(d.getUTCMonth() + 1) + "/" +
              pad(d.getUTCDate()) +
              " at " +
              pad(d.getUTCHours()) + ":" +
              pad(d.getUTCMinutes());
    let text = `
# Generated by penguins-eggs
DEFAULT vesamenu.c32
PROMPT 0
TIMEOUT 30
MENU TITLE CD/DVD ${name} ${version} ${at}
MENU TABMSG Press TAB key to edit
MENU BACKGROUND eggs.png

LABEL ${this.distroName}
  MENU LABEL ^${this.distroName}
  kernel /live/vmlinuz
  append boot=live initrd=/live/initrd.img quiet splash

label ${this.distroName} install
  MENU LABEL ^${this.distroName} install
  kernel /live/vmlinuz
  append boot=live initrd=/live/initrd.img quiet splash finstall

label ${this.distroName} safe
  MENU LABEL ^${this.distroName} safe
  kernel /live/vmlinuz
  append boot=live initrd=/live/initrd.img xforcevesa nomodeset quiet splash`;
    utils.bashwrite(file, text);

    let path = utils.path();
    utils.exec(`cp ${path}/src/assets/eggs.png ${this.isoDir}/isolinux`);
  }


  alive() {
    utils.exec(`cp /vmlinuz ${this.isoDir}/live/`);
    utils.exec(`cp /initrd.img ${this.isoDir}/live/`);
  }

  squashFs() {
    let option = "-comp xz";
    utils.exec(
      `mksquashfs ${this.fsDir} ${this
        .isoDir}/live/filesystem.squashfs ${option} -noappend`
    );
  }

  makeIso() {
    let isoHybridOption = "-isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin ";
    //let uefiOption = "";
    //"-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot";
    let volid = `"${this.distroName}"`;
    let isoName = `${this.distroRoot}/${this.distroName}`;
    let d = new Date();
    let ver =
      "_" +
      pad(d.getUTCFullYear()) +
      "-" +
      pad(d.getUTCMonth() + 1) +
      "-" +
      pad(d.getUTCDate()) +
      "_at_" +
      pad(d.getUTCHours()) +
      pad(d.getUTCMinutes());
    isoName += ver + ".iso";

    utils.exec(
      `xorriso -as mkisofs -r -J -joliet-long -l -cache-inodes ${isoHybridOption} -partition_offset 16 -A ${volid} -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ${isoName} ${this
        .isoDir}`
    );
  }
}

function pad(number) {
  if (number < 10) {
    return "0" + number;
  }
  return number;
}

export default Iso;
