/*
  utils.js V. 0.3.0
*/
// require('./commands').forEach(function (command) {
//  require('./utils/' + command);
//});
("use strict");

let shell = require("shelljs");
let fs = require("fs");

let utils = function() {};

// require('./commands').forEach(function (command) {
//  require('./utils/' + command);
//});

utils.prototype.bashwrite = function(file, text) {
  const head = `########################################################START##
# Generated by Egg ${file.trim()}
###############################################################\n`;
  const footer = `######################################################## END ##
`;

  console.log(`[utils]\n>>> Creazione ${file}`);
  text = head + text.trim() + "\n" + footer;
  text = text.trim() + "\n";
  file = file.trim();
  fs.writeFileSync(file, text);
  console.log(text);
  console.log(`>>> Fine creazione ${file}  ===`);
};

utils.prototype.exec = function(cmd) {
  console.log(`[utils] >>> exec ${cmd}`);
  shell.exec(cmd);
};

utils.prototype.rsync = function(commands) {
  console.log(`[utils] >>> rsync ${commands}`);
  commands.forEach(function(cmd) {
    // Questa riga, mandava rsync in async...
    //const { stdout, stderr, code } =  shell.exec(cmd, { silent: true });
    shell.exec(cmd,{async:false});

  });
};

utils.prototype.sr = function(file, search, replace) {
  fs.readFile(file, "utf8", function(err, data) {
    if (err) {
      return console.log(err);
    }
    let result = data.replace(search, replace);
    fs.writeFile(file, result, "utf8", function(err) {
      if (err) return console.log(err);
    });
  });
};

module.exports = new utils();
