/*
  utils.js V. 0.3.0
*/

"use strict";

let shell = require("shelljs");
let fs = require("fs");


function rsync(commands) {
  commands.forEach(function(cmd) {
    console.log(cmd);
    const { stdout, stderr, code } = shell.exec(cmd, { silent: true });
  });
};

function exec(cmd) {
  console.log(cmd);
  shell.exec(cmd);
};

function bashfile(file, text) {
  const head = `
###############################################################
# Generated by Egg
###############################################################
`;
  const footer = `###############################################################
`;

  console.log(`### Creazione ${file}  ###`);
  text = head + text + footer;
  console.log(text);
  fs.writeFile(file, text, function(err) {
    if (err) {
      console.log(`Errore durante la scrittura di ${file}, errore: ${err}`);
    }
  });
  console.log(`### Fine creazione ${file}  ###`);
};

function fileSearchReplace(file, search, replace) {
  fs.readFile(file, "utf8", function(err, data) {
    if (err) {
      return console.log(err);
    }
    let result = data.replace(search, replace);
    fs.writeFile(file, result, "utf8", function(err) {
      if (err) return console.log(err);
    });
  });
};

module.exports = ['rsync', 'exec', 'bashfile', 'fileSearchReplace;
                  
